### ISSUE TITLE
use Ansible to build➜label➜push docker images

### ISSUE THREAD

**Issue by dminca** [skullops/dockerfiles#7]
Put all the CI/CD weight on Ansible instead of the `Makefile`

**Comment by dminca** [comment]
- For `$BUILD_DATE` ARG use Ansible's `ansible_date_time.iso8601` formatted according RFC3339 as seen:

``` yml
"ansible_date_time": {
    "date": "2016-11-05", 
    "day": "05", 
    "epoch": "1478308914", 
    "hour": "03", 
    "iso8601": "2016-11-05T01:21:54Z", 
    "iso8601_basic": "20161105T032154083946", 
    "iso8601_basic_short": "20161105T032154", 
    "iso8601_micro": "2016-11-05T01:21:54.084119Z",
    "minute": "21", 
    "month": "11", 
    "second": "54", 
    "time": "03:21:54", 
    "tz": "EET", 
    "tz_offset": "+0200", 
    "weekday": "sâmbătă", 
    "weekday_number": "6", 
    "weeknumber": "44", 
    "year": "2016"
}
```
- for anything else like `$VCS_URL, $VCS_REF, $VERSION` use Ansible's [docker_image](https://docs.ansible.com/ansible/docker_image_module.html) module with argument `buildargs` and `key:value` eg:

``` yml
- name: Build image and with buildargs
   docker_image:
     path: /path/to/build/dir
     name: myimage
     buildargs:
       log_volume: /var/log/myapp
       listen_port: 8080
```
- `build_args` must be set as:

``` sh
docker build \
  --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
  --build-arg VERSION=$(CODE_VERSION) \
  --build-arg VCS_URL=`git config --get remote.origin.url` \
  --build-arg VCS_REF=$(GIT_COMMIT) \
-t $(DOCKER_IMAGE):$(DOCKER_TAG) .
```
